.github/workflows/checks.yaml, .github/workflows/deploy.yml, .github/workflows/test-deploy.yml, README.md, docusaurus.config.js
Document is now hosted in root instead of under openfga.github.io page.
Close https://github.com/openfga/openfga.dev/issues/14
=> chore: update build script to point to correct CNAME

docs/content/integration/advanced/search-with-permissions.mdx, docs/content/integration/perform-check.mdx, docs/content/intro/openfga-concepts.mdx, docs/content/modeling/basics/contextual-time-based-authorization.mdx, docs/content/modeling/basics/organization-context-authorization.mdx, docs/content/modeling/concepts/usersets.mdx, docs/content/writing-data/advanced/check-read-expand.mdx, docs/content/writing-data/transactional-writes.mdx, docusaurus.config.js, src/components/SwaggerUI/swagger-ui.tsx
Swap docusaurus configuration to point to the actual swagger file. Also need to update links to API service as tags are different.
Close https://github.com/openfga/openfga.dev/issues/7
=> chore: swap to point to new swagger document

docs/content/modeling/configuration-language.mdx
When discussing Zanzibar equivalent, display authorization model in
DSL and API separately to allow clearer understanding of difference.
https://user-images.githubusercontent.com/10730463/172890324-bc533b8e-b10d-46be-9792-88b014b75845.mov
Close https://github.com/openfga/openfga.dev/issues/5
=> feat: update configuration language page equivalent section for language

docs/content/modeling/advanced/patterns/entitlements.mdx
Fix typo in entitlement page.  Should read `plan:y` instead of `play:y`.
Close https://github.com/openfga/openfga.dev/issues/19
=> fix: typo in entitlement page

static/css/openfga.css
Adjustable scroll targets for docs Table of Contents links.
This uses the :target pseudoelement, with a negative margin and height to make it possible for us to adjust the offset from the top of the viewport when a user clicks on TOC links to scroll to a heading within a docs page. See the following before/after comparing the currently deployed site at openfga.dev vs. the branch used for this PR:
This closes #31
=> feat: adjustable scroll targets for docs

src/features/LandingPage/HeroHeader/HeroHeader.module.css
Adjusted logo size on hero element across two breakpoints.
At some point the logo in the hero component was reduced in size until on desktop it more or less matched the subtitle below it. The plan (based on our Figma mockups) was to have the logo larger and more prominent, so that it can be recognized as distinct from the other text.
I've adjusted the size on mobile and desktop breakpoints to match the mockups.
Before:
After:
=> style:logo sizing for hero element

src/features/LandingPage/HeroHeader/index.tsx
Fix to re-enable showing and hiding of header logo when hero logo is visible.
At some point we lost the `ref={headerRef}` that we use for detecting when the hero logo is in view.
=> fix: reveal and hide header logo upon scroll

src/features/LandingPage/HeroHeader/index.tsx
Change link to https://github.com/openfga
https://user-images.githubusercontent.com/10730463/173119811-d06ef1fa-47eb-46d6-a4c1-f5d6693b42d4.mov
Close https://github.com/openfga/openfga.dev/issues/36
=> fix: link on hero landing page to github

src/components/SwaggerUI/swagger-ui-override.css
Style cleanup on API page
The API page had some styling inconsistencies to resolve:
* Border and background style on Delete endpoints
* Chevrons for API sections weren't aligned
Before:
After:
Closes #54
=> style: remove red outlines, align chevrons on API page

static/css/openfga.css
Add styling for details and summary box
Close https://github.com/openfga/openfga.dev/issues/56
=> fix: styling in details/summary box

docusaurus.config.js, src/pages/index.tsx
Update so that the correct title is in the document home page
Close https://github.com/openfga/openfga.dev/issues/32
=> fix: update metadata title to correct page title

src/components/Docs/AuthorizationModel/AuthzModelSnippetViewer.tsx, src/components/Docs/SnippetViewer/WriteAuthzModelViewer.tsx, src/components/Docs/SnippetViewer/index.ts
Provides a component that showcases posting the Authorization Model to the API.
CSS needs a bit of a touch up for nested components (the paddings are weird, and the admonition has a lot of extra space)
https://user-images.githubusercontent.com/536147/173605916-83c6147d-a776-48c4-b07d-58727afddd6a.mov
To test:
- Import the `WriteAuthzModelViewer` component directly and pass in an authorization model
- Pass `showWrite={true}` to the `AuthzModelSnippetViewer`
=> feat: add write authorization model viewer component

src/features/LandingPage/HeroHeader/HeroLogo.tsx
Corrected viewbox of HeroLogo svg so that the trademark doesn't get cut off. ✨ 
Before:
After:
Closes #76
=> fix: HeroLogo viewbox wasn't sized properly

docusaurus.config.js
Allow handling of slashes at the end of the URL link so that it does not lead to 404
https://user-images.githubusercontent.com/10730463/173844983-54cf091c-8137-4b8e-9b02-96e2c6ac0673.mov
Close https://github.com/openfga/openfga.dev/issues/48
=> fix: handle slashes at end of URL link

docs/README.md, docs/content/getting-started/configure-model.mdx, docs/content/getting-started/framework.mdx, docs/content/getting-started/overview.mdx, docs/content/getting-started/perform-check.mdx, docs/content/getting-started/update-tuples.mdx, docs/sidebars.js, src/components/Docs/SnippetViewer/WriteAuthzModelViewer.tsx
Add page in getting-started section on how to configure authorization
model (after store is created and SDK is setup).
https://user-images.githubusercontent.com/10730463/173669118-768d36e6-a525-4182-88d6-3439e7a9cd16.mov
Close https://github.com/openfga/openfga.dev/issues/35
=> feat: add configure model page

src/features/LandingPage/ResourcesSection/ResourcesSection.module.css, static/css/openfga.css
1. Fix problem where mobile browser cannot see menu.
2. Landing pages require horizontal scaling due to resource section
margin not set properly for mobile browser.
https://user-images.githubusercontent.com/10730463/174092684-6d959bba-9403-4c2b-bc3c-d87b1da6f0f8.mov
- Close https://github.com/openfga/openfga.dev/issues/87
- Close https://github.com/openfga/openfga.dev/issues/78
=> fix: mobile browser cannot see menu + margin issue

docs/content/getting-started/setup-openfga.mdx
1. Change to run command `run`.
2. Instruct reader to do `docker pull` to ensure they have the latest image.
To match changes provided by https://github.com/openfga/openfga/pull/48
=> chore: update docker running instruction

static/css/openfga.css
1. Disable mobile search bar's focus/not focus transition as it causes
consecutive transition during initial search.
2. Reduce width of search bar during focus so that it does not block
the logo.
https://user-images.githubusercontent.com/10730463/174353109-8bf21ef1-c772-4d85-8792-2a0fe2cfaf4c.mov
- Close https://github.com/openfga/openfga.dev/issues/103
- Close https://github.com/openfga/openfga.dev/issues/102
=> fix: disable mobile search bar transition and update width

.github/workflows/checks.yaml
Allow `npm audit` to fail due to update-notifier dependency by Docusaurus.
=> chore: allow npm audit to fail

src/components/Docs/AuthorizationModel/SyntaxTransformer.ts
We do not support Friendly1 syntax. Thus, remove it from syntax
transformer.
=> chore: remove un-needed apiToFriendlySyntaxV1 function

src/features/LandingPage/HeroHeader/index.tsx, src/pages/api/service.tsx, static/css/openfga.css
Added a class to the containing `#__docusaurus` div in order to help identify different views in css rules.
In order to hide the logomark's text (`OpenFGA`) from view by default on the landing page, and ensure that it shows on the Docs and APIs page, we need a unique identifier that we can use in CSS rules.
Open to any different ideas on how to achieve this, but one line of JS in the respective views seemed simple and durable enough.
=> feat: add classes to allow showing and hiding header logo per view/route

docs/content/getting-started/setup-openfga.mdx
The environment variable needs to be before the image name.  In addition, the invocation needs to pass in the option run.
=> fix: incorrect order of parameters in docker run

.gitignore
File is used by Snyk analysis and can be ignored.
=> chore: ignore .dccache file

src/components/Docs/SnippetViewer/WriteAuthzModelViewer.tsx
The current `curl` example for creating an authorization model uses the `/stores/<store_id>/write` endpoint. The correct endpoint is `/stores/<store_id>/authorization-models`.
=> Fixes incorrect endpoint for creating an authorization model

src/features/LandingPage/HeroHeader/index.tsx
The previous strategy for selecting video formats was always evaluating false in a build environment.
In order to keep the execution environment check from always making our useragent check return false, I'm wrapping the logic in a <BrowserOnly> component instead. Thanks @adriantam for the catch. 🙇 
- Corrects #83 
- Addresses original issue #51
=> Fix: hero video switch

static/img/openfga-icon.svg
A reformatted SVG favicon based on our original intended design, with some CSS to change the fill colour based on whether the browser is in lightmode or darkmode.
A nice by-product of this is the actual number of pixels allotted to the logo design is a bit larger, because it doesn't need the framing black shape.
Before: 
After:
=> feat: reformat favicon to support light/darkmode

docs/content/getting-started/setup-openfga.mdx
It wasn't clear to me that playground is at path `/playground`. Propose to clarify that
Clarify that "playground" is reachable only on path `/playground`. The existing docs made me thing it would be available at `http://<host>:3000` since only the port number was mentioned
=> chore: clarify playground url in openfga server setup

docs/content/getting-started/setup-openfga.mdx
The original docker-compose example didn't work for me. Proposing an improved compose where the migrate command is run inline instead of manually.
Update the example docker-compose file to run the "migrate" step automatically, instead of having to do that in a separate shell command (which didn't work when I attempted it)
=> improve docker-compose example

docusaurus.config.js
GitHub should read GitHub
close https://github.com/openfga/openfga.dev/issues/199
=> fix: correct github label in navbar

docs/content/getting-started/create-store.mdx, docs/content/getting-started/setup-sdk-client.mdx, src/components/Docs/SnippetViewer/CheckRequestViewer.tsx, src/components/Docs/SnippetViewer/ExpandRequestViewer.tsx, src/components/Docs/SnippetViewer/ListObjectsRequestViewer.tsx, src/components/Docs/SnippetViewer/ReadChangesRequestViewer.tsx, src/components/Docs/SnippetViewer/ReadRequestViewer.tsx, src/components/Docs/SnippetViewer/SdkSetup.tsx, src/components/Docs/SnippetViewer/WriteAuthzModelViewer.tsx, src/components/Docs/SnippetViewer/WriteRequestViewer.tsx
Change to python SDK callout as async python requires await
- https://github.com/openfga/sdk-generator/pull/29
=> feat: switch to use async python

docs/content/modeling/getting-started.mdx, src/components/Docs/Feedback/Callout.tsx, src/features/LandingPage/FeaturesSection/index.tsx
Cleanup include by having static asset include to use alias instead of hard coded link
Close https://github.com/openfga/openfga.dev/issues/223
https://docusaurus.io/docs/next/static-assets
=> chore: static asset should use alias

package-lock.json, package.json, src/components/Docs/AuthorizationModel/SyntaxTransformer.ts
Switch to use openfga's syntax-transformer when switching between model
Close https://github.com/openfga/openfga.dev/issues/16
=> chore: switch to use syntax-transformer

src/components/Docs/SnippetViewer/CheckRequestViewer.tsx
Check was missing closing bracket if there are no context 
https://user-images.githubusercontent.com/10730463/194071888-04d5eaa4-7e33-4d5d-b3ac-44f1e178d3b7.mov
https://user-images.githubusercontent.com/10730463/194071906-954c6729-ebca-4487-b642-287725a1d12f.mov
Close https://github.com/openfga/openfga.dev/issues/228
=> fix: incorrect golang check callout

.snyk
Extend to end of year as the underlying docusaurus still use an out of date update-notifier due to presence of non-ES modules.
=> chore: extend synk ignore for SNYK-JS-GOT-2932019

src/components/Docs/SnippetViewer/ReadRequestViewer.tsx
Correct JS callout for read by ensuring there is a closing quote.  Also updated spacing for .NET SDK read callout
Close https://github.com/openfga/openfga.dev/issues/231
=> fix: correct JS callout for read

docs/content/interacting/search-with-permissions.mdx
Update search's option 3 to use ListObject.
Close https://github.com/openfga/openfga.dev/issues/239
=> feat: update search to link to list object

package-lock.json, package.json
Override minimatch 3.0.4 to 3.0.5 for snyk identified vulnerability
=> chore: override minimatch for snyk vulnerability

docs/content/concepts.mdx, docs/content/configuration-language.mdx, docs/content/getting-started/configure-model.mdx, docs/content/interacting/managing-group-access.mdx, docs/content/interacting/managing-group-membership.mdx, docs/content/interacting/managing-relationships-between-objects.mdx, docs/content/interacting/managing-user-access.mdx, docs/content/interacting/read-tuple-changes.mdx, docs/content/interacting/relationship-queries.mdx, docs/content/interacting/transactional-writes.mdx, docs/content/modeling/advanced/entitlements.mdx, docs/content/modeling/advanced/gdrive.mdx, docs/content/modeling/advanced/github.mdx, docs/content/modeling/advanced/iot.mdx, docs/content/modeling/advanced/slack.mdx, docs/content/modeling/blocklists.mdx, docs/content/modeling/building-blocks/concentric-relationships.mdx, docs/content/modeling/building-blocks/direct-relationships.mdx, docs/content/modeling/building-blocks/object-to-object-relationships.mdx, docs/content/modeling/building-blocks/usersets.mdx, docs/content/modeling/contextual-time-based-authorization.mdx, docs/content/modeling/custom-roles.mdx, docs/content/modeling/direct-access.mdx, docs/content/modeling/getting-started.mdx, docs/content/modeling/multiple-restrictions.mdx, docs/content/modeling/organization-context-authorization.mdx, docs/content/modeling/parent-child.mdx, docs/content/modeling/public-access.mdx, docs/content/modeling/roles-and-permissions.mdx, docs/content/modeling/user-groups.mdx
1. Tagging model as version 1.1
2. Run format document 
See corresponding change for https://github.com/openfga/syntax-transformer/pull/80. We should tag version so that the correct version will be shown for DSL.
=> chore: tag model schema as version 1.1

docs/content/getting-started/setup-openfga.mdx
Add a brief note about configuration overrides through environment variables.
In version [`v0.1.6`](https://github.com/orgs/openfga/discussions/14), a feature created the ability to override configuration files options through environment variables. It's something very useful to know when deploying OpenFGA, and there isn't any reference yet in the documentation about it. 
This PR adds a simple note in the configuration section to tell people that it's possible to use environment variables. 
There is no references.
=> docs: add guidelines about environment variables

static/img/cncf-icon-white.svg
The CNCF logo had its colours reversed in the *Features* section and footer, and the grey used was implemented with #FFF and opacity 0.75 instead of the correct colour code. This PR matches their brand guidelines.
Ref:
Before:
After:
- https://www.cncf.io/brand-guidelines/#logo
=> Update cncf logo to adhere to brand guidelines

src/components/Docs/SnippetViewer/WriteAuthzModelViewer.tsx
Do not use validate_and_convert_types as it is not available in our current python SDK.
Close https://github.com/openfga/openfga.dev/issues/281
=> fix: correct python write model example

docs/content/getting-started/setup-sdk-client.mdx
Should use Credentials instead of writing DefaultHeader
Close https://github.com/openfga/openfga.dev/issues/292
=> fix: update .NET SDK setup example

.github/workflows/checks.yaml, .github/workflows/deploy.yml, .github/workflows/test-deploy.yml, Dockerfile
Update both docker and github actions to use nvm 18
=> chore: use nvm 18

docs/content/concepts.mdx, docs/content/interacting/transactional-writes.mdx, docs/content/modeling/advanced/gdrive.mdx, docs/content/modeling/building-blocks/direct-relationships.mdx, docs/content/modeling/public-access.mdx
With changes to wildcard type restriction, we need to update examples for public access to indicate type is required.
Close https://github.com/openfga/openfga.dev/issues/279
=> chore: update public access example for type restriction

docs/content/interacting/relationship-queries.mdx, docs/content/modeling/migrating/migrating-schema-1-1.mdx, src/components/Docs/SnippetViewer/CheckRequestViewer.tsx, src/components/Docs/SnippetViewer/ExpandRequestViewer.tsx, src/components/Docs/SnippetViewer/ListObjectsRequestViewer.tsx, src/components/Docs/SnippetViewer/ReadRequestViewer.tsx, src/components/Docs/SnippetViewer/SupportedLanguage.tsx, src/components/Docs/SnippetViewer/WriteRequestViewer.tsx
For Check, Expand, Read, Write, ListObject API callout, include authorization model id.  In addition, mention obtaining authorization model id as first step in migrating schema.
https://user-images.githubusercontent.com/10730463/207643663-4e86044d-54fd-4ede-a103-935d77f861ac.mov
https://user-images.githubusercontent.com/10730463/207643918-7f3675dd-1857-44a6-b068-d11211afbdf1.mov
Close https://github.com/openfga/openfga.dev/issues/307
=> feat: add authorization model in callout

src/components/Docs/SnippetViewer/WriteRequestViewer.tsx
Correct the .NET callout for write.  It should be `AuthorizationModelId="xxx"` instead of `authorization_model_id:"xxx"`
=> fix: dotnet write callout authorization model id

src/components/Docs/SnippetViewer/CheckRequestViewer.tsx, src/components/Docs/SnippetViewer/ExpandRequestViewer.tsx, src/components/Docs/SnippetViewer/ReadRequestViewer.tsx
Read does not take in authorization model id
Also, the .NET Request should use {} if we want to use optional parameter such as AuthorizationModelId.
=> fix: read does not use authorization id

docs/content/modeling/migrating/migrating-schema-1-1.mdx
Migration schema page should not tell user to read for particular authorization model id.
=> fix: read does not have authorization model id

docusaurus.config.js, package-lock.json, static/css/openfga.css
Change the docusaurus footer config to make sure the trademark and copyright info satisfies clomonitor.
Currently we have a very bare-bones footer:
The clomonitor service looks for a different trademark URL in order to be satisfied that we're accounting for The Linux Foundation's trademark ownership:
`"https://(?:w{3}\.)?linuxfoundation.org/trademark-usage"`
While updating that, I've added some additional words and links in order to be more complete:
And added a CSS rule to hide part of it and simplify the footer on mobile:
https://clomonitor.io/docs/topics/checks/#trademark-disclaimer
=> fix: update trademark line to satisfy clomonitor

docs/content/getting-started/setup-sdk-client.mdx
Current docs are incorrect for how to pass the bearer token in the JS client. This PR corrects the docs.
=> Fix js docs for client with shared key

docs/README.md, docs/content/getting-started/overview.mdx, docs/content/getting-started/production-best-practices.mdx, docs/content/getting-started/production-environment.mdx, docs/content/getting-started/setup-openfga.mdx, docs/content/modeling/migrating/migrating-relations.mdx, docs/content/modeling/migrating/migrating-schema-1-1.mdx, docs/sidebars.js
Move production environment into its own page.  In addition, add additional materials to the page.
https://user-images.githubusercontent.com/10730463/207924593-bd37a5be-c67b-448c-be4e-fe1044c11994.mov
Close https://github.com/openfga/openfga.dev/issues/312
=> chore: move production environment into its own page

docs/content/concepts.mdx, docs/content/modeling/advanced/gdrive.mdx, docs/content/modeling/building-blocks/direct-relationships.mdx, docs/content/modeling/public-access.mdx
Make it more clear that you cannot use type:* syntax in the object field.  Also, move the warning closer to the section where it is used.
Close https://github.com/openfga/openfga.dev/issues/328
=> fix: clean up warning for wildcard syntax usage

docs/content/modeling/getting-started.mdx
Add missing organization member relationship
Close https://github.com/openfga/openfga.dev/issues/333
=> fix: add missing member relationship

docs/content/modeling/getting-started.mdx
Small tweak to the [getting started doc](https://openfga.dev/docs/modeling/getting-started). When describing how to create a definition for the "can_view" relation, the sentence states 
>"A user can view a document if they are an owner, viewer or editor of a document or if they are a viewer, owner of the folder/drive that is the parent of the document."
But the actual definition is as follows
>    define can_view: viewer or editor or viewer from parent or owner from parent
Which is missing a direct owner relation. This is fixed in the final auth model.
=> fix: add owner to can_view relation definition in getting started

docs/content/getting-started/setup-openfga.mdx
Remove reference to pause.  In addition, reformat to be similar to https://github.com/openfga/openfga/blob/main/docker-compose.yaml.
Close https://github.com/openfga/openfga.dev/issues/359
=> fix: update docker-compose file to be similar to openfga github

docs/content/configuration-language.mdx, docs/content/modeling/migrating/migrating-schema-1-1.mdx, docs/content/modeling/parent-child.mdx, src/components/Docs/AuthorizationModel/AuthzModelSnippetViewer.tsx, src/components/Docs/SnippetViewer/CheckRequestViewer.tsx
We do not evaluate the tupleset part of a relation definition, which may not be expected. In [OpenFGA `v0.2.4`](https://github.com/orgs/openfga/discussions/59) we took the decision to actually consider that a security issue and throw an error when encountered.
The main problem remains that we do not properly warn against this in the documentation. This PR attempts to add a bit of words of caution.
It doesn't look too pretty, but it (hopefully) gets the point across.
- Closes #265
=> chore(docs): add a note about openfga not evaluating the tupleset

docs/content/modeling/migrating/migrating-relations.mdx, src/components/Docs/SnippetViewer/ReadRequestViewer.tsx
If only type is specified for read tuples, we must also provide the username. For migration, it is better to read all tuples instead of per relation/object type.
https://user-images.githubusercontent.com/10730463/223235832-d90eadd7-f0f9-4584-8aea-5bdde7247649.mov
Close https://github.com/openfga/openfga.dev/issues/381
=> fix: correct migration relations read tuples

docs/content/modeling/advanced/assets/github-org-base-permissions-drop-down.png, docs/content/modeling/advanced/github.mdx
GitHub deleted the file from their docs - replaced it with a manual screenshot
=> fix: member access image in github guide

docusaurus.config.js
The CSP (Content Security Policy) for github is not correctly - preventing github star from being displayed properly.  Also update CSP for hubspot.
https://community.hubspot.com/t5/HubSpot-Ideas/A-guide-to-Content-Security-Policy-CSP-settings/idi-p/314328
=> fix: correct CSP for github star

src/components/Docs/SnippetViewer/CheckRequestViewer.tsx
=> fix: correct .NET SDK check snippet bracket closing order

docs/content/interacting/relationship-queries.mdx
Add proper caution box in list object explanation
=> fix: correct caution box in list object explanation

docs/content/modeling/building-blocks/object-to-object-relationships.mdx
Explain how to choose user vs. object with entitlement's feature vs. plan as example
Based off of Discord message https://discord.com/channels/759188666072825867/1098436392595501066/1098600845790154772
=> feat: add explanation of feature vs plan when used in entitlement

docs/content/modeling/migrating/migrating-schema-1-1.mdx, docusaurus.config.js
Remove migrating schema 1.1 document's note about deprecation
Close https://github.com/openfga/openfga.dev/issues/450
=> chore: remove migrating schema 1.1 document

docusaurus.config.js
=> fix: change link to openfga github

docs/content/configuration-language.mdx
Fix reference to correct type `writer` instead of `editor`.
https://openfga.dev/docs/configuration-language
=> fix: typo in configuration language documentation

docs/content/getting-started/create-store.mdx, docs/content/modeling/advanced/github.mdx, docs/content/modeling/migrating/migrating-relations.mdx
Add directly assignable relationships to example so that DSL is rendered correctly
Close https://github.com/openfga/openfga.dev/issues/477
=> fix: github and migration examples specified directly assignable relationship

src/components/Docs/SnippetViewer/WriteRequestViewer.tsx
Aims to close #512  by fixing the commands used on the docs to write and delete tuples
=> fix: write and delete references on docs

docs/content/modeling/getting-started.mdx
In `Get Started With Modelling` mention that we can do direct relationship type restriction
Close https://github.com/openfga/openfga.dev/issues/514
=> fix: update get started with modelling on direct relationship type restriction

blog/conditional-tuples-announcement.md
=> fix(blog): better highlighting in conditional tuples blog

docs/content/modeling/advanced/entitlements.mdx, docs/content/modeling/advanced/gdrive.mdx, docs/content/modeling/advanced/github.mdx, docs/content/modeling/getting-started.mdx
Update a few docs with grammatical fixes, minor edits for clarity, and some fixes for non-rendering OpenFGA code
I'm a new OpenFGA user and when reading the docs I noticed a few things that appeared to be typos or were slightly unclear. I also noticed that a few of the code snippets did not render correctly, for example this one on https://openfga.dev/docs/modeling/advanced/gdrive:
In this PR I've attempted improve the things I noticed, but I am not an expert in the project, so just let me know if you'd like me to change anything.
N/A
- (N/A) I have added tests to validate that the change in functionality is working as expected
=> Minor doc cleanup

src/css/custom.css, static/css/openfga.css
The size of the navbar calculated by the layout does not match the actual navbar size, which results in the navbar overlapping the side navigations.
This pull request resolves the issue by defining the navbar height as a custom CSS variable and applying it within the header.
https://github.com/openfga/openfga.dev/assets/41171734/fbe45e27-023d-49d2-8832-4490230b3d97
https://github.com/openfga/openfga.dev/assets/41171734/353eb71b-68d6-471f-9777-6fe922c036e3
=> fix: navbar overlapping page content

docs/content/modeling/getting-started.mdx
This change corrects the assertion that Beth does not have the **can_share** relationship with `document:1`, even though she is an editor of it.
_The relationship definition._
_Relationship tuples._
_Old assertion._
_Fixed assertion._
=> Fix the assertion within the 'Get Started with Modeling' page.

package-lock.json, package.json
Styling changes in https://github.com/swagger-api/swagger-ui/compare/v5.9.3...v5.9.4 causes weirdness in styling.  Temporary downgrade swagger-ui while working out the new styling config.
Workaround for https://github.com/openfga/openfga.dev/issues/578
=> chore: downgrade swagger-ui

src/components/SwaggerUI/swagger-ui-override.css
This PR resolves remaining style problems following the update to the new swagger-ui version (#579, #580) by implementing some adjustments in CSS.
- #580 
- #579
=> chore: adjust some remaining css properties from new swagger-ui version

README.md
No need to refer to which version of Docusaurus - otherwise, README needs to be updated every time an external project has a major version bump.
=> chore: use generic docusaurus instead of which version of docusaurus

docs/content/getting-started/setup-openfga/configure-openfga.mdx, docs/content/getting-started/setup-openfga/playground.mdx
Minor fixes from previous merge
=> chore: improved title structure

docs/content/modeling/overview.mdx
Corrects the link to the Conditions page
Closes #593
=> Correct link to conditions page

docs/content/interacting/managing-group-access.mdx, docs/content/interacting/managing-group-membership.mdx, docs/content/interacting/managing-relationships-between-objects.mdx, docs/content/interacting/managing-user-access.mdx, docs/content/interacting/transactional-writes.mdx, docs/content/modeling/blocklists.mdx, docs/content/modeling/building-blocks/concentric-relationships.mdx, docs/content/modeling/building-blocks/direct-relationships.mdx, docs/content/modeling/building-blocks/object-to-object-relationships.mdx, docs/content/modeling/contextual-time-based-authorization.mdx, docs/content/modeling/custom-roles.mdx, docs/content/modeling/direct-access.mdx, docs/content/modeling/getting-started.mdx, docs/content/modeling/multiple-restrictions.mdx, docs/content/modeling/organization-context-authorization.mdx, docs/content/modeling/parent-child.mdx, docs/content/modeling/public-access.mdx, docs/content/modeling/roles-and-permissions.mdx, docs/content/modeling/user-groups.mdx, src/components/Docs/CardBox/CardBox.module.css
This PR fixes formatting issues with `CardBox` in the current documentation.  Passing content as an MDX formatted `description` causes the content to lack proper markdown formatting because the mdx parser does not apply to component props. Passing the content as `children` fixes the issue and feels more idiomatic as well.
=> fix: fixes format issues with cardbox uses

docs/content/getting-started/create-store.mdx, docs/content/getting-started/framework.mdx, docs/content/getting-started/setup-sdk-client.mdx, docusaurus.config.js, src/components/Docs/SnippetViewer/CheckRequestViewer.tsx, src/components/Docs/SnippetViewer/ExpandRequestViewer.tsx, src/components/Docs/SnippetViewer/ListObjectsRequestViewer.tsx, src/components/Docs/SnippetViewer/ReadChangesRequestViewer.tsx, src/components/Docs/SnippetViewer/ReadRequestViewer.tsx, src/components/Docs/SnippetViewer/SdkSetup.tsx, src/components/Docs/SnippetViewer/WriteAuthzModelViewer.tsx, src/components/Docs/SnippetViewer/WriteRequestViewer.tsx
Fixes the Go snippet for writing a model and also cleans up other snippets to make corrections where necessary and some formatting changes.
Closes #614
=> docs: cleanup Go snippets

docs/content/modeling/conditions.mdx, docs/content/modeling/contextual-time-based-authorization.mdx, src/components/Docs/SnippetViewer/CheckRequestViewer.tsx, src/components/Docs/SnippetViewer/ListObjectsRequestViewer.tsx, src/components/Docs/SnippetViewer/ReadChangesRequestViewer.tsx, src/components/Docs/SnippetViewer/WriteRequestViewer.tsx
Adds support for context/condition, continuation token and corrects the contextual tuples logic within the CLI snippets
Part of #603
Draft until context/condition and continuation token support is released in the CLI
=> docs(cli): document usage of context/condition and continuation token

.github/workflows/preview.yml
PRs from dependabot dont have the permissions required to be able to deploy, so lets just skip them.
This should still allow us to deploy if a real person other than dependabot triggers the workflow on the branch as `github.actor` will point to them not dependabot
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events
#626 where the PR fails to deploy due to permissions
=> ci(preview): dont attempt to deploy previews from dependabot PRs

docs/content/authorization-and-openfga.mdx
Fix typo (?) reference to AuthZ instead of AuthN
This commit fixes a reference that should have been to AuthN made in the AuthN-vs-AuthZ description section which might be confusing for beginners.
[Documentation on AuthN vs AuthZ](https://openfga.dev/docs/authorization-and-openfga#authentication-vs-authorization)
- [-] I have added tests to validate that the change in functionality is working as expected
=> fix(docs): AuthZ mentioned instead of AuthN

docs/content/authorization-and-openfga.mdx
Correcting a few typos noticed in the authorization and Openfga page.
Two small spelling/grammatical fixes.
=> fix(docs): fix typo in "authorization and openfga" 

docs/content/modeling/testing-models.mdx
- Add `actions/checkout` to fetch the content of the repository.
- The version `v0.1` does not resolve. Changed it its used version to `v0.1.0`.
Error in the CI logs:
```console
Error: Unable to resolve action `openfga/action-openfga-test@v0.1`, unable to find version `v0.1`
```
See the action on the github marketplace: https://github.com/marketplace/actions/openfga-model-testing-action
=> fix: `openfga-model-testing-action` example in docs

.github/workflows/markdown.links.config.json, blog/authors.yml, blog/modular-models-announcement.md, docs/content/modeling/modular-models.mdx, docs/sidebars.js, src/theme/prism-include-languages.ts, static/img/blog/authors/ewan.jpg
Adds a first pass at a blogpost and documentation guide for modular models.
I wasn't really certain on how best to structure the documentation so went with a "follow along" style based on our canonical example of jira/confluence (although I've removed that naming).
I'm planning to re-read this again later so there may be some edit (hence draft PR currently) but feel free to take a review, additionally I'm just using plain codeblocks currently for the module files currently as there's no real way to express these right now (we don't have a JSON way to store them).
=> chore: add modular models blog and explainer doc

docs/content/getting-started/create-store.mdx
The change updates the `jq` example for exporting FGA_STORE_ID. The new API response does not work with the example jq.
Example response of the new FGA API:
```json
{
"store": {
"created_at":"2024-04-09T05:52:22.078257Z",
"id":"01HV0PM8HY355M5G4GTW3VQ4E5",
"name":"FGA Demo Store",
"updated_at":"2024-04-09T05:52:22.078257Z"
}
}
```
- `jq -r .id` - 🚫
- `jq -r .store.id` - ✅ 
I don't mean to be nit-picking, but as I start to learn OpenFGA and read through the wonderful docs, I try to help fix any problems (however small they may be)
N/A
=> fix: jq expression in create store shell example

docs/content/getting-started/cli.mdx
`--simple-output` seems to be deprecated in the CLI, replaced by `--output-format=simple-json`
The example has been updated to reflect that change.
> Note: Sorry for many small PRs, but I find these as I go in my learning :)
=> fix: CLI output-format example

src/components/Docs/SnippetViewer/CheckRequestViewer.tsx, src/components/Docs/SnippetViewer/ListObjectsRequestViewer.tsx
Fixes the casing for providing contextual tuples in code snippets for check and list objects.
https://github.com/openfga/sdk-generator/issues/346
=> fix(snippets/js): correct casing for contextual tuples in check and list objects

blog/fine-grained-news-2024-04.md
=> feat: add Fine Grained News for April

docs/content/concepts.mdx, docs/content/getting-started/perform-list-users.mdx, docs/content/modeling/testing-models.mdx, docs/sidebars.js, package-lock.json, package.json, src/components/Docs/SnippetViewer/ListUsersRequestViewer.tsx, src/components/Docs/SnippetViewer/index.ts
* 30aaf25016608937b4870eda07e38edb80d9d1e8 - Adds the snippet viewer for list users, the python implementation is currently a guess as it's not implemented
* f6dba22dd4ad63e1a2895974ea6f2708d4bc1776 - Adds docs for list users to the concepts page, the testing guide, and a perform list users page. The latter two include a warning banner that states the experimental nature and link to the announcement.
=> Add list users snippet, concept and testing

docs/content/concepts.mdx, docs/content/getting-started/perform-list-users.mdx, src/components/Docs/SnippetViewer/ListUsersRequestViewer.tsx
Building off #732, this PR adds sections for public wildcards and excluded users for the List Users API. Also correcting the response shape in the two examples listed.
=> ListUsers: wildcards, excluded users and minor fixes

docs/content/intro.mdx
Fix a bad link in documentation intro page: previous "Python" link lead to java sdk and not python sdk.
=> fix: resolve wrong python SDK Link in intro

docs/content/getting-started/perform-list-users.mdx
Adds the "Known Limitations" section to highlight ListUsers's missing functionality while it is in the experimental phase.
Also a couple minor adjustments bundled:
- Making the API name consistent, "List Users"
- Converting existing example response into JSON
=> List Users - "Known Limitations" section

docs/content/getting-started/perform-list-users.mdx, src/components/Docs/SnippetViewer/ListUsersRequestViewer.tsx
Adds support for producing a python example for the list users snippet code
=> feat: add python to list users snippet

docs/content/getting-started/setup-openfga/configure-openfga.mdx
This PR updates the logging documentation to include an important warning about enabling logs in production environments. Disabling logging by setting `--log-level` to `none` can mask important operations and hinder the ability to detect and diagnose issues, including potential security incidents.
Related https://github.com/openfga/openfga/issues/1703
=> Add warning about enabling logs in production to logging documentation

docs/content/getting-started/perform-list-users.mdx
Removing the ListUsers experimental warning as a show of confidence for production usage.
Related PRs: (soon to come)
=> Remove ListUsers experimental warning

docs/content/modeling/advanced/gdrive.mdx
Erik is mentioned in text to be a allowed viewer of the document when describing 'type bound public access' in Google Drive. But the code snippet says false. Took me some time to figure out.
The relevant [text](https://openfga.dev/docs/modeling/advanced/gdrive#03-folder-permission-propagation:~:text=Erik%20is%20NOT%20a%20member%20of%20the%20xyz.com%20domain%2C%20and%20so%20can%20only%20view%20the%20document) in the documentation.
=> fix: fix incorrect response in Gdrive modelling guide

blog/fine-grained-news-2024-07.md, blog/query-consistency-options-announcement.md
I renamed this post:
https://openfga.dev/pr-preview/pr-802/blog/query-consistency-options-announcement
And updated the link to it here:
https://openfga.dev/pr-preview/pr-802/blog/fine-grained-news-2024-07
=> fix(blog)!: rename 'stronger' to 'query' consistency options

docs/content/concepts.mdx, docs/content/configuration-language.mdx, docs/content/getting-started/production-best-practices.mdx, docs/content/interacting/relationship-queries.mdx, docs/content/modeling/advanced/entitlements.mdx, docs/content/modeling/advanced/iot.mdx, docs/content/modeling/advanced/slack.mdx, docs/content/modeling/building-blocks/direct-relationships.mdx, docs/content/modeling/building-blocks/object-to-object-relationships.mdx, docs/content/modeling/getting-started.mdx, docs/content/modeling/roles-and-permissions.mdx, docusaurus.config.js, src/components/Docs/ProductName/ProductName.tsx
Fixes some links that have occurred due to refactoring and renaming of pages, the following warnings still exist but are not issues because it's down to docusaurus having issues locating the element rather than it not existing (this has been manually verified)
<details>
<summary>Docusaurus output</summary>
```
Exhaustive list of all broken anchors found:
- Broken anchor on source page path = /docs/concepts:
-> linking to /api/service#Relationship%20Queries/Check
-> linking to /api/service#Relationship%20Queries/ListObjects
-> linking to /api/service#Relationship%20Queries/ListUsers
- Broken anchor on source page path = /docs/getting-started/configure-model:
-> linking to /api/service#Authorization%20Models/WriteAuthorizationModel
- Broken anchor on source page path = …
```
=> fix: correct some broken links due to site changes

blog/query-consistency-options-announcement.md
Small grammatical fix to L:13
From: OpenFGA query APIs now allows to specify the desired consistency of query results.
To: OpenFGA query APIs now allow specifying the desired consistency of query results.
=> fix(grammar): Update query-consistency-options-announcement.md

docs/content/interacting/read-tuple-changes.mdx
I removed the paragraph below as it's not accurate for OpenFGA
"The API response will not return all the changes immediately. There will be a delay of one minute between the time that you add or delete a tuple and the time that you see it in the Read Changes API response."
=> fix: remove inaccurate note in ReadChanges

docs/content/getting-started/perform-check.mdx, docs/content/getting-started/setup-openfga/configure-openfga.mdx, docs/content/interacting/relationship-queries.mdx, docs/content/interacting/search-with-permissions.mdx, src/components/Docs/SnippetViewer/BatchCheckRequestViewer.tsx, src/components/Docs/SnippetViewer/index.ts
Adding documentation to the "Perform a Check" doc giving the option to perform a Batch Check using the new API endpoint. 
- Added a new "Calling Batch Check API" section under the normal batch check
- Explained the purpose of the `correlation_id`, mentioning that the SDK handles it automatically (or it at least will very soon). 
- Created a BatchCheckRequestViewer component, but only with the CURL language, since the SDKs are not done. 
=> feat: Add docs for new Batch Check API endpoint

docs/content/getting-started/immutable-models.mdx
=> chore: added a new scenario for immutable models

src/components/Docs/SnippetViewer/CheckRequestViewer.tsx, src/components/Docs/SnippetViewer/ListObjectsRequestViewer.tsx, src/components/Docs/SnippetViewer/ListUsersRequestViewer.tsx
The type in Python is `ClientTuple` https://github.com/openfga/python-sdk/#list-objects
=> fix: correct type for contextual tuples in python

package-lock.json, package.json
Reverts openfga/openfga.dev#901
Original merge is causing the search to fail
closes https://github.com/openfga/openfga.dev/issues/907
=> Revert "chore(deps): bump @easyops-cn/docusaurus-search-local from 0.45.0 to 0.46.1 in the dependencies group across 1 directory"

docs/content/modeling/migrating/migrating-models.mdx, docs/content/modeling/migrating/overview.mdx, docs/sidebars.js
Moves the content for migrating models into a dedicated page so that the general theme of overview pages linking to child content is maintained.
=> refactor: move migrating models content to its own page

docs/content/interacting/transactional-writes.mdx
Add documentation about write request limitations regarding duplicate tuples.
fixes #919
=> docs: Add warning about duplicate tuples in write requests

src/components/Docs/SnippetViewer/ListUsersRequestViewer.tsx
Fixes #934
A missing " in ListUsersRequestViewer.tsx led to a missing " in the documentation for list-users:
https://github.com/openfga/openfga.dev/blob/c144f0b701479ebd303e94ee6218ca6b05adaeef/src/components/Docs/SnippetViewer/ListUsersRequestViewer.tsx#L58
=> fix:  insert missing " in list-users documentation

docs/content/getting-started/cli.mdx
The current document only describes how the CLI tool authenticates with OIDC, yet named as pre-shared key authn.
This PR includes the actual Pre-shared Key Authn parameter for the CLI tool.
=> chore: Include CLI setting for Pre-shared key Authn

docs/content/getting-started/setup-openfga/configuration.mdx, package.json, scripts/update-config-page.mjs
This is the script that generates the page in #938 
It can be run using: `npm run update:config-page`
=> feat: add script to autogenerate  configuration page

docs/content/interacting/relationship-queries.mdx
Including more ways to call the Read API that were not previously documented.
Updating the documentation to include all 7 ways you can use the Read API to get relationship tuples.
1. Read a tuple related to a particular user, relation, and object
2. Read all tuples related to a particular user, relation, and object type
3. Read all tuples related to a particular user and object with any relation
4. Read all tuples related to a particular user and object type with any relation
5. Read all tuples related to a particular relation and object for any user
6. Read all tuples related to a particular object with any user or relation
7. Read all tuples for any user, relation, or object
1,4,6,7 were previously not documented. 
Addresses issue https://github.com/openfga/openfga.dev/issues/971
=> updating the types of valid read calls someone can make

docs/content/community.mdx
Added proper link to new meeting calendar
=> Added proper link to new meeting calendar

docs/content/best-practices/source-of-truth.mdx, docs/sidebars.js
=> feat: adding source of truth document

.github/workflows/markdown.links.config.json, docs/content/best-practices/modeling.mdx, docs/sidebars.js
=> feat: adding modeling best practices

docs/content/getting-started/setup-openfga/playground.mdx
Corrected grammar on bullet regarding tuple limit within Playground
Very small grammatical edit. Self-evident in the diff.
N/A
=> docs: Minor grammar fix on Playgrounds page

docs/content/getting-started/setup-openfga/configure-openfga.mdx
Changes the limit from 128 to 255 for mysql limits in the documentation.
https://github.com/openfga/openfga/pull/2230
=> Docs: update limit for mysql from 128 to 255

docs/content/getting-started/setup-openfga/configuration.mdx
=> chore(docs): bump docs for OpenFGA v1.8.9

docs/content/getting-started/cli.mdx
Added a line to indicate `fga tuple delete --file=(csv|json|yaml)` now supports CSV as well.
1. [feat: support csv in fga tuple delete](https://github.com/openfga/cli/pull/478)
=> doc: `fga tuple delete --file=(csv|json|yaml)` now supports CSV

src/components/Docs/SnippetViewer/BatchCheckRequestViewer.tsx, src/components/Docs/SnippetViewer/CheckRequestViewer.tsx
This is not python
Dict keys must be inside quotes and field atribution must use colon (instead of equal)
https://openfga.dev/docs/getting-started/perform-check
=> fix: python check call snippets

src/components/Docs/SnippetViewer/BatchCheckRequestViewer.tsx
This fixes a bug in `BatchCheckRequestViewer.tsx` where the Python SDK code generator was emitting `ClientBatchCheckItem` calls without a closing parenthesis, resulting in invalid Python examples on the site. Each `ClientBatchCheckItem(...)` is now properly closed with `)` and items are separated with commas, producing valid Python syntax.
```python
checks = [
ClientBatchCheckItem(
user="user:anne",
relation="writer",
object="document:Z",
correlation_id="886224f6-04ae-4b13-bd8e-559c7d3754e1",
ClientBatchCheckItem(
user="user:anne",
relation="reader",
object="document:Z",
correlation_id="da452239-a4e0-4791-b5d1-fb3d451ac078"
]
checks = [
ClientBatchCheckItem(
user="user:anne",
relation="writer",
object="document:Z",
correlation_id="886224f6-04ae-4b13-bd8e-559c7d3754e1"
), …
```
=> fix(viewer): add missing parenthesis in Python SDK code rendering

README.md, blog/fine-grained-news-2024-02.md, blog/fine-grained-news-2024-03.md, docs/README.md, docs/content/getting-started/framework.mdx, docs/content/modeling/advanced/iot.mdx, docs/content/modeling/advanced/slack.mdx, docusaurus.config.js
=> fix: rebranding okta fga to auth0 fga

src/components/Docs/SnippetViewer/CheckRequestViewer.tsx
=> fix: typo in Authorization Model ID

docs/content/modeling/testing-models.mdx
=> chore: add example for modular models

.github/workflows/checks.yaml, docs/content/modeling/advanced/slack.mdx, docs/content/modeling/user-groups.mdx
`gaurav-nelson/github-action-markdown-link-check` was recently deprecated and recommends `tcort/github-action-markdown-link-check`, a fork maintained by the author of the npm package.
I don't think this is the cause of the failures we've been seeing in the action, but it's a sensible change to make and allows testing out any potential issues.
=> ci: replace deprecated link check action

docs/content/interacting/relationship-queries.mdx
Remove `The new BatchCheck endpoint is currently supported by the JS SDK (>=[v0.8.0](https://github.com/openfga/js-sdk/releases/tag/v0.8.0) and the Python SDK (>=[v0.9.0](https://github.com/openfga/python-sdk/releases/tag/v0.9.0)). Support in the other SDKs is being worked on.` and replaced it with a clearer note
=> fix(docs): remove batchcheck endpoint support to js/python sdk note

docs/content/getting-started/setup-openfga/configure-openfga.mdx
Introduced detailed guidance on configuring OpenFGA with PostgreSQL read replicas to enhance performance and scalability. This update includes instructions for setting up primary and secondary datastores, considerations for synchronous vs. asynchronous replication, and best practices for ensuring data consistency and monitoring replication lag.
https://github.com/openfga/openfga/pull/2479
=> feat: add support for PostgreSQL read replicas in OpenFGA configuration
