openfga/openfga.dev

package-lock.json
package.json
src/components/Docs/Banner/Banner.tsx
src/components/Docs/CardBox/CardBox.tsx
src/components/Section/index.tsx
src/pages/api/service.tsx

Bumped Dependencies
Bumped Dependencies

chore: bumped deps

---

src/utils/prism-openfga-dsl.js

This drops a log statement that is happening at build time that we do not need.
Closes #47

chore: cleanup prism log in `npm run build`

---

static/css/openfga.css

Fixed hover/active styling for Table of Contents
- Fixed hover/active styling for Table of Contents
- Closes #39 
https://user-images.githubusercontent.com/3803431/173605103-b5f93cb1-1725-4793-b172-5d3a127e5a76.mov

style: adjusted styling in table of contents

---

package-lock.json
package.json
src/theme/prism-include-languages.d.ts
src/theme/prism-include-languages.ts

Keeping code to be typescript for consistency.

chore: update prism-include-language to typescript

---

docs/content/interacting/check-read-expand.mdx
docs/content/modeling/building-blocks/usersets.mdx
docs/content/modeling/contextual-time-based-authorization.mdx
docs/content/modeling/getting-started.mdx

Fix broken link in getting started page.  Also remove un-used component import
- Close https://github.com/openfga/openfga.dev/issues/91

fix: broken link in getting started page

---

docs/content/authorization-and-openfga.mdx
docs/content/concepts.mdx
docs/content/getting-started/configure-model.mdx
docs/content/getting-started/framework.mdx
docs/content/getting-started/install-sdk.mdx
docs/content/getting-started/perform-check.mdx
docs/content/interacting/check-read-expand.mdx
docs/content/interacting/search-with-permissions.mdx
docs/content/interacting/transactional-writes.mdx
docs/content/modeling/advanced/gdrive.mdx
docs/content/modeling/advanced/github.mdx
docs/content/modeling/advanced/slack.mdx
docs/content/modeling/blocklists.mdx
docs/content/modeling/building-blocks/usersets.mdx
docs/content/modeling/contextual-time-based-authorization.mdx
docs/content/modeling/organization-context-authorization.mdx

Correct incorrect anchor location

fix: correct bad anchor

---

docs/content/authorization-and-openfga.mdx

In the introductory paragraph, add .NET to list of SDK.  In addition, provide links to the various SDKs

chore: add link to SDK and mention .NET

---

docs/content/getting-started/setup-openfga.mdx
docs/content/getting-started/setup-sdk-client.mdx

Update production checklist
- Depends on a few PRs being merged:
- https://github.com/openfga/openfga/pull/2
- https://github.com/openfga/openfga/pull/31
n/a

chore: update production checklist

---

docs/content/authorization-and-openfga.mdx
docs/content/concepts.mdx
docs/content/configuration-language.mdx
docs/content/getting-started/install-sdk.mdx
docs/content/interacting/read-tuple-changes.mdx
docs/content/modeling/advanced/github.mdx
docs/content/modeling/building-blocks/object-to-object-relationships.mdx
docs/content/modeling/contextual-time-based-authorization.mdx

- Re-worded the "what is openfga?" section (https://openfga.dev/docs/authorization-and-openfga#what-is-openfga)
- Removed cases of "word word"
- Grammar fixes
- Typo fixes
n/a

fix: various pages

---

src/components/SwaggerUI/swagger-ui-override.css

For mobile browser:
- reduce spacing in method button
- do not set max-width
- do not display summary description
https://user-images.githubusercontent.com/10730463/174157299-523a418b-32b6-40e4-86de-7348a26a34e4.mov
Close https://github.com/openfga/openfga.dev/issues/97

fix: correct styling in /api/service page for mobile browser

---

docs/content/getting-started/install-sdk.mdx
docs/content/getting-started/setup-sdk-client.mdx
src/components/Docs/SnippetViewer/SdkSetup.tsx

| Before | After |
| --- | --- |
| <img width="983" alt="Screen Shot 2022-06-16 at 6 55 22 PM" src="https://user-images.githubusercontent.com/536147/174191633-3e7c9a19-e878-475d-bc6a-32c36b824e3a.png"> | <img width="908" alt="Screen Shot 2022-06-16 at 6 55 11 PM" src="https://user-images.githubusercontent.com/536147/174191662-d5e5633c-5148-41dc-8850-0ee213e80290.png"> |
| <img width="988" alt="Screen Shot 2022-06-16 at 6 54 41 PM" src="https://user-images.githubusercontent.com/536147/174191713-503fdb67-ae83-44a5-afeb-f593f6eb56ba.png"> | <img width="908" alt="Screen Shot 2022-06-16 at 6 54 58 PM" src="https://user-images.githubusercontent.com/536147/174191742-5dcbccf1-4afd-485c-b8a7-b7c08e7db5b2.png"> |
| <img width="988" alt="Screen Shot 2022-06-16 at 6 54 19 PM" …

fix: update sdk setup snippets

---

README.md

Update for the link to security policy etc.

chore: update link in README file

---

package-lock.json
package.json

Dependency Updates
- eslint and typescript updates

chore: dependency updates Jun  20

---

src/components/Docs/Banner/Playground.tsx

Update playground description text to include playground name
for intro section.
- Close https://github.com/openfga/openfga.dev/issues/137

fix: playground description text

---

src/features/LandingPage/FeaturesSection/index.tsx

Remove unused import
- Close https://github.com/openfga/openfga.dev/issues/138

chore: remove unused import in Features section

---

package-lock.json
package.json

chore: upgrade to docusaurus rc-1

---

.snyk
package-lock.json

Ignore these two issues until end of September:
- [SNYK-JS-AUTOLINKER-2438289](https://security.snyk.io/vuln/SNYK-JS-AUTOLINKER-2438289)
- [SNYK-JS-GOT-2932019](https://security.snyk.io/vuln/SNYK-JS-GOT-2932019)

chore(security): add snyk policy file

---

src/components/Docs/SnippetViewer/ListObjectsRequestViewer.tsx

chore: add sdks to ListObjectsViewer component

---

docs/content/getting-started/setup-openfga.mdx

Add a quick note on how to use docker compose to spin up OpenFGA with Postgres
https://user-images.githubusercontent.com/536147/185657683-025ce618-d10f-4766-b990-5601945b7942.mov
Migrate can be simplified once this issue is tackled: https://github.com/openfga/openfga/issues/163

chore(setup): add docker compose instructions

---

docs/README.md
docs/content/concepts.mdx
docs/content/interacting/overview.mdx
docs/content/interacting/relationship-queries.mdx
docs/content/interacting/search-with-permissions.mdx
docs/sidebars.js
src/components/Docs/SnippetViewer/ListObjectsRequestViewer.tsx
src/components/Docs/SnippetViewer/index.ts

This adds the official doc for the ListObjects API.
https://github.com/openfga/openfga/pull/164

docs: add ListObjects documentation

---

docs/content/concepts.mdx
docs/content/interacting/managing-group-access.mdx
docs/content/interacting/managing-group-membership.mdx
docs/content/interacting/managing-relationships-between-objects.mdx
docs/content/interacting/managing-user-access.mdx
docs/content/interacting/relationship-queries.mdx
docs/content/interacting/transactional-writes.mdx
docs/content/modeling/blocklists.mdx
docs/content/modeling/building-blocks/concentric-relationships.mdx
docs/content/modeling/building-blocks/direct-relationships.mdx
docs/content/modeling/building-blocks/object-to-object-relationships.mdx
docs/content/modeling/contextual-time-based-authorization.mdx
docs/content/modeling/direct-access.mdx
docs/content/modeling/multiple-restrictions.mdx
docs/content/modeling/organization-context-authorization.mdx
docs/content/modeling/parent-child.mdx
docs/content/modeling/public-access.mdx
docs/content/modeling/roles-and-permissions.mdx
docs/content/modeling/user-groups.mdx

Clean up the organization and wordings for the following documents
- Contextual and Time-Based Authorization
- Authorization Through Organization Context
https://user-images.githubusercontent.com/10730463/186951794-e4a59c20-3416-4f78-b4a7-b4968ad6ea25.mov
https://user-images.githubusercontent.com/10730463/186951853-14ddc22b-1bce-416d-8a6c-16a782404ed4.mov
- Close https://github.com/openfga/openfga.dev/issues/182

fix: clean up organization and proof edit context docs

---

package-lock.json
package.json

chore: upgrade dependency packages

chore: update dependency packages

---

docusaurus.config.js
src/features/LandingPage/FeaturesSection/index.tsx
static/css/openfga.css
static/img/cncf-icon-white.svg

Update OpenFGA webpage to be compliant with CNCF guideline
https://user-images.githubusercontent.com/10730463/191626918-6d08e4c2-14b6-415f-b55a-d2b8b70b1f90.mov
See https://github.com/cncf/foundation/blob/main/website-guidelines.md

feat: update documentation to be CNCF compliant

---

package-lock.json
package.json

chore: bump swagger-ui-react pkg

---

package-lock.json
package.json
src/components/Docs/AuthorizationModel/AuthzModelCodeBlock.tsx
src/components/Docs/AuthorizationModel/AuthzModelSnippetViewer.tsx
src/components/Docs/AuthorizationModel/SyntaxTransformer.ts

1. Remove unused lodash import and upgrade packages.
2. Update authorization model callout due to changes in OpenFGA SDK
N/A

chore: remove unused lodash and upgrade packages

---

docs/README.md
docs/content/modeling/migrating-relations.mdx
docs/content/modeling/overview.mdx
docs/sidebars.js
package-lock.json

Guide on how to migrate relationship tuples
Close https://github.com/openfga/openfga.dev/issues/256

feat: documentation on migrating relationship tuples

---

package-lock.json
package.json

Bump dependency packages - especially loader-utils which have vulnerability
N/A

chore: bump dependency packages

---

package-lock.json
package.json
src/components/Docs/AuthorizationModel/AuthzModelCodeBlock.tsx
src/utils/prism-openfga-dsl.js
static/css/openfga.css

feat: add schema v1.1 syntax highlighting

---

src/components/Docs/SnippetViewer/ListObjectsRequestViewer.tsx

The response is now objects instead of object_ids
Brought on by https://github.com/openfga/sdk-generator/pull/78

chore: update list object sample response

---

docs/content/interacting/relationship-queries.mdx

fix: list objects not showing the correct response format

---

docs/content/getting-started/setup-openfga.mdx

Add a section to the Setup OpenFGA page documenting Experimental Features and how to enable them.

docs: add an Experimental Features section to the Setup OpenFGA page

---

docs/content/configuration-language.mdx

Minor update for config language page's description
N/A

fix: minor changes to config language description

---

docs/content/getting-started/setup-openfga.mdx

Add a Telemetry section to the Setup OpenFGA page to assist developers with configuring telemetry.

docs: add Telemetry section to Setup OpenFGA page

---

package-lock.json
package.json

chore of override eta package.  
override package for https://security.snyk.io/vuln/SNYK-JS-ETA-2936803

chore: override eta package

---

docs/content/modeling/multiple-restrictions.mdx
docs/content/modeling/user-groups.mdx

We had incorrect type restrictions in some places after the update to 1.1 schema version
Closes #336 
Closes #353

fix(docs): fix type restrictions in User Groups and Multiple Restrictions 

---

docs/content/getting-started/setup-openfga.mdx

Add in details for how to configure pre-shared and OIDC authentication
https://user-images.githubusercontent.com/10730463/217037453-70990ce4-4998-43ce-9f34-857e3a72b5df.mov
Close https://github.com/openfga/openfga.dev/issues/331

feat: add details to authentication (pre-shared and OIDC)

---

docs/content/getting-started/configure-model.mdx

fix(docs): configure authz model was missing user type

---

docs/content/getting-started/configure-model.mdx
docs/content/getting-started/perform-check.mdx
docs/content/getting-started/update-tuples.mdx
package-lock.json
package.json
tsconfig.json

Bump packages - including docusaurus.  Notice that upgrading docusaurus package requires listing TabItem individually.

chore: bump packages

---

package-lock.json
package.json

Resolves an issue preventing loading JS in Safari (due to lookbehind regex)

chore(deps): update syntax-transformer

---

docs/content/getting-started/tuples-api-best-practices.mdx

Minor grammar correction for tuples and api best practice page
Code review feedback https://github.com/openfga/openfga.dev/pull/366 post-merge

fix: correcting tuples and api best practice page

---

docs/content/getting-started/overview.mdx
docs/sidebars.js

Rename to "Implementation Best Practices"
N/A

chore: update sidebar name of best practice

---

docs/content/modeling/migrating/migrating-schema-1-1.mdx
docusaurus.config.js

feat: add schema v1.0 deprecation timeline

---

package-lock.json
package.json
src/theme/prism-include-languages.ts

Override `package-json@6.5.0` to `7.0.0` as that brings in a newer version of `got` and resolves the single security alert we had.
| Tool | Previously | After this change |
| --- | --- | --- |
| Snyk | <img width="1247" alt="Screen Shot 2023-03-02 at 9 48 50 AM" src="https://user-images.githubusercontent.com/536147/222463477-4c42f555-5ba2-4c7c-932a-f4c067a44a1e.png"> | |
| Dependabot | <img width="1222" alt="Screen Shot 2023-03-02 at 9 50 44 AM" src="https://user-images.githubusercontent.com/536147/222463556-8a4d4aec-49cd-41ba-aa8c-56810bcf9fce.png"> | |
| npm audit | <img width="240" alt="Screen Shot 2023-03-02 at 9 48 15 AM" src="https://user-images.githubusercontent.com/536147/222463609-921579ce-5073-44e8-ba88-99c4a34a071b.png"> | <img width="413" alt="Screen Shot 2023-03-02 at 9 54 20 …

chore(deps): upgrade deps and override `package-json`

---

docs/content/getting-started/create-store.mdx
docs/content/getting-started/setup-openfga.mdx

Pre-requisite: https://github.com/openfga/openfga/pull/605 ✅

fix: setup instructions

---

Dockerfile

resolves: https://security.snyk.io/vuln/SNYK-ALPINE317-CURL-3320725

chore: remove curl from the dev docker image

---

docs/content/getting-started/setup-sdk-client.mdx

Fix typo in Python import statement

fix: typo in Python import statement

---

package-lock.json
package.json

- Blocked by openfga/syntax-transformer#123

chore(deps): bump syntax-transformer

---

docs/content/interacting/relationship-queries.mdx

chore: update the ListObjects section

---

.github/workflows/deploy.yml
docusaurus.config.js

feat: add HubSpot snippet

---

docusaurus.config.js

fix: loading hubspot script

---

src/components/Docs/SnippetViewer/CheckRequestViewer.tsx

This PR contains fix for .NET C# example for Calling Check API related to #418 issue.

Update check snippet for DOTNET_SDK

---

docs/README.md
docs/content/concepts.mdx
docs/content/getting-started/overview.mdx
docs/content/getting-started/perform-list-objects.mdx
docs/content/interacting/relationship-queries.mdx
docs/sidebars.js

1. Add page that describe how to use list objects
2. Add what is list objects request in product concept section
https://github.com/openfga/openfga.dev/assets/10730463/ec8afbce-a281-4b98-8321-8332cab56531
Close https://github.com/openfga/openfga.dev/issues/447

feat: add page for list objects

---

docs/content/getting-started/immutable-models.mdx
docs/content/getting-started/overview.mdx
docs/sidebars.js

feat: add a page describing immutable models

---

package-lock.json
package.json

chore(deps): override semver

---

docs/content/getting-started/production-best-practices.mdx

Explain more fine-tuning to do on the OpenFGA server settings.
Related to https://github.com/openfga/openfga/pull/829

feat: explain max connections

---

docs/content/modeling/building-blocks/direct-relationships.mdx

Fix missing metadata info
Close https://github.com/openfga/openfga.dev/issues/459

fix: direct relationship building block model missing metadata

---

docs/content/getting-started/configure-model.mdx
docs/content/getting-started/create-store.mdx
docs/content/getting-started/framework.mdx
docs/content/getting-started/install-sdk.mdx
docs/content/getting-started/perform-check.mdx
docs/content/getting-started/perform-list-objects.mdx
docs/content/getting-started/setup-sdk-client.mdx
docs/content/getting-started/update-tuples.mdx
docs/content/interacting/read-tuple-changes.mdx
docs/content/interacting/transactional-writes.mdx
docusaurus.config.js
src/components/Docs/SnippetViewer/CheckRequestViewer.tsx
src/components/Docs/SnippetViewer/ExpandRequestViewer.tsx
src/components/Docs/SnippetViewer/ListObjectsRequestViewer.tsx
src/components/Docs/SnippetViewer/ReadChangesRequestViewer.tsx
src/components/Docs/SnippetViewer/ReadRequestViewer.tsx
src/components/Docs/SnippetViewer/SdkSetup.tsx
src/components/Docs/SnippetViewer/SupportedLanguage.tsx
src/components/Docs/SnippetViewer/WriteAuthzModelViewer.tsx
src/components/Docs/SnippetViewer/WriteRequestViewer.tsx

- Adds client credential flow to setup
- In the SDKs Switches from the `OpenFgaApi` to `OpenFgaClient`
- Adds a tab for the CLI
- closes #441 
- closes #474

feat: add CLI, add client credentials flow & switch to new SDK clients

---

.npm-upgrade.json
package-lock.json
package.json
src/components/Docs/Banner/Banner.module.css
src/components/Docs/SnippetViewer/CheckRequestViewer.tsx
src/components/Docs/SnippetViewer/ListObjectsRequestViewer.tsx
src/components/Docs/SnippetViewer/WriteRequestViewer.tsx
src/components/SwaggerUI/swagger-ui-override.css
src/pages/api/service.tsx

None of the breaking changes affect us

chore(deps): upgrade dependencies

---

docs/content/getting-started/framework.mdx

```
> const jwt-authenticate = require('./jwt-authenticate');
const jwt-authenticate = require('./jwt-authenticate');
^^^
Uncaught SyntaxError: Missing initializer in const declaration
```
https://openfga.dev/docs/getting-started/framework

fix: update to prevent uncaught syntax error

---

README.md
docs/README.md
docs/content/authorization-and-openfga.mdx
docs/content/concepts.mdx
docs/content/getting-started/configure-model.mdx
docs/content/modeling/advanced/slack.mdx
docusaurus.config.js
src/components/Docs/AuthorizationModel/AuthzModelSnippetViewer.tsx

feat: update branding

---

.github/workflows/markdown.links.config.json
docusaurus.config.js

feat: add link to blog

---

blog/authors.yml

fix: andres's profile photo

---

docs/content/modeling/contextual-time-based-authorization.mdx

Fix missing text in contextual time based authorization docs
Links render correctly, see https://openfga.dev/docs/modeling/organization-context-authorization#summary
Missing links, see https://openfga.dev/docs/modeling/contextual-time-based-authorization#summary

Add missing import

---

blog/conditional-tuples-announcement.md

Added blog announcement for conditional tuples

Added conditional tuples blog announcement

---

src/components/Docs/AuthorizationModel/SyntaxTransformer.ts

fix: show partial type defs

---

blog/conditional-tuples-announcement.md

Mentioned that the playground does not support conditional tuples yet

Updated Conditional Tuples Blog

---

docs/content/modeling/advanced/entitlements.mdx
docs/content/modeling/advanced/gdrive.mdx
docs/content/modeling/getting-started.mdx
src/components/Docs/AuthorizationModel/SyntaxTransformer.ts

chore: allow showing just type defs, error out when parsing not possible

---

docusaurus.config.js
src/components/Docs/SnippetViewer/SdkSetup.tsx
src/components/Docs/SnippetViewer/WriteRequestViewer.tsx

Some of the generated python code is not correct

fix: correct python callout

---

static/css/openfga.css

| Before | After |
|--------|--------|
| <img width="928" alt="image" src="https://github.com/openfga/openfga.dev/assets/55068936/598bb1b1-7f40-4559-b552-bf17659b517f"> | <img width="930" alt="image" src="https://github.com/openfga/openfga.dev/assets/55068936/79fd4324-0df7-4829-a912-1595ca45eec3"> | 
fixes #77

Adjust pre and details padding in markdown dropdown codeblocks

---

docusaurus.config.js

chore: temporarily pin api docs to not include conditions

---

docs/content/concepts.mdx
docs/content/modeling/abac-conditions.mdx
docs/content/modeling/conditions.mdx
docs/sidebars.js
docusaurus.config.js
src/components/Docs/RelationshipTuples/Viewer.tsx
src/components/Docs/SnippetViewer/CheckRequestViewer.tsx
src/components/Docs/SnippetViewer/ListObjectsRequestViewer.tsx
src/components/Docs/SnippetViewer/WriteAuthzModelViewer.tsx
src/components/Docs/SnippetViewer/WriteRequestViewer.tsx

Add documentation on ABAC Conditions and Conditional Relationship Tuples in preparation for the upcoming `v1.4.0` release with ABAC support.

docs(abac): add initial ABAC Condition documentation

---

docs/content/modeling/getting-started.mdx
package-lock.json
package.json

fix: resolve invalid json models in getting started + bump transformer

---

docs/README.md
docs/content/modeling/overview.mdx

Adding links in overview and README page

chore: add links to overview page

---

blog/fine-grained-news-2023-12.md
static/img/blog/fgn-2023-12-bdd.png
static/img/blog/fgn-2023-12-canonical.png
static/img/blog/fgn-2023-12-language.png
static/img/blog/fgn-2023-12-validation.png

https://openfga.dev/pr-preview/pr-600/blog/fine-grained-news-2023-12

Add FGN December 2023 edition

---

.github/CODEOWNERS

chore: change owner team

---

docs/content/getting-started/production-best-practices.mdx

See https://openfga.dev/pr-preview/pr-642/docs/getting-started/running-in-production

feat: new section on prod best practices

---

docs/content/authorization-and-openfga.mdx

Full rework of the doc, including copyedits, style guide update, and clarity.

chore(docs): update Authorization and OpenFGA document

---

docs/content/getting-started/create-store.mdx
docs/content/getting-started/framework.mdx
docs/content/getting-started/install-sdk.mdx
docs/content/getting-started/setup-sdk-client.mdx
src/components/Docs/SnippetViewer/SdkSetup.tsx

Replaces any remaining usage of scheme/host configuration with url
- [] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]

chore: replace host/scheme usage with url

---

docs/content/openfga-support.mdx
docusaurus.config.js

https://openfga.dev/pr-preview/pr-665/docs/support

feat(docs): added openfga support page

---

.github/workflows/preview.yml

chore(ci): set base path for PRs

---

docs/content/modeling/advanced/github.mdx

Fix for a model snippet in the Github example where a relation was referenced with the wrong name.
For this example, there's a relation where a repo can have an organization as owner. Admins rights on the repo are gained through an indirect relationship. The relation on the repo references the relation on the organization by the wrong name.

docs: fix relation reference in github model example

---

blog/fine-grained-news-2024-02.md

https://openfga.dev/pr-preview/pr-669/blog/fine-grained-news-2024-02

feat(blog): Added FGN Februrary 2024

---

docs/content/modeling/token-claims-contextual-tuples.mdx

fix: update token-claims-contextual-tuples to fix user id

---

.github/CODEOWNERS
.github/workflows/markdown.links.config.json
docs/content/community.mdx

https://openfga.dev/pr-preview/pr-680/docs/community

chore(docs): update the community page

---

docs/content/modeling/token-claims-contextual-tuples.mdx

chore:fix typo in contextual tuples doc

---

docs/content/modeling/conditions.mdx

chore: fixed typo

---

docs/content/intro.mdx

chore: fix typo

---

docs/content/getting-started/perform-list-objects.mdx
docs/content/interacting/search-with-permissions.mdx

chore: improvements in listobjects scenarios doc

---

docs/content/community.mdx

chore: set the time and timezone link for community meetings

---

blog/modular-models-announcement.md

I somehow jumped a month into the future when writing this I guess

chore: correct modular models blog date

---

blog/fine-grained-news-2024-03.md

https://openfga.dev/pr-preview/pr-706/blog/fine-grained-news-2024-03

Adding FGN March Edition

---

blog/modular-models-announcement.md

chore: update modular models announcement

---

blog/fine-grained-news-2024-05.md
blog/list-users-announcement.md

https://openfga.dev/pr-preview/pr-754/blog/fine-grained-news-2024-05
https://openfga.dev/pr-preview/pr-754/blog/list-users-announcement

chore: added fgn and adjusted list users announcement

---

src/components/Docs/SnippetViewer/WriteAuthzModelViewer.tsx

CLI instructions need value to be surrounded in single quotes for zsh users. Also need to specify that the format is json.

fix: it should set format to json and surround value in single quotes

---

blog/fine-grained-news-2024-06.md
static/img/blog/fgn-2024-06-securitycon-booth.png
static/img/blog/fgn-2024-06-securitycon-talk.jpg

https://openfga.dev/pr-preview/pr-780/blog/fine-grained-news-2024-06

June Fine Grained News

---

docs/content/intro.mdx

Fixed a missing word in the docs
a word was missing
none

fix: full name of the CNCF

---

blog/stronger-consistency-options-announcement.md
docs/content/interacting/consistency.mdx
docs/sidebars.js

https://openfga.dev/pr-preview/pr-799/blog/stronger-consistency-options-announcement
https://openfga.dev/pr-preview/pr-799/docs/interacting/consistency

Adding higher consistency parameter documentation

---

.gitattributes
blog/authors.yml
blog/fine-grained-news-2024-07.md
static/img/blog/authors/caleb.jpg

Add Fine Grained News July 2024 edition

feat(blog): add July 2024 Fine Grained News

---

docs/content/getting-started/setup-openfga/configure-openfga.mdx

Depends on https://github.com/openfga/openfga/pull/1784 getting released

feat: update docs regarding OIDC authentication

---

docs/content/interacting/transactional-writes.mdx

change 10 unique tuples to 100 unique tuples for write api

Update transactional-writes.mdx typo

---

docs/content/interacting/managing-group-access.mdx
docs/content/interacting/transactional-writes.mdx
docs/content/modeling/parent-child.mdx
docs/content/modeling/roles-and-permissions.mdx

Fixes to:
- Transactional Writes
- Roles and Permissions
- Managing Group Access
- Parent-Child
Integrating changes from pavokta-patch-1, pavokta-patch-2, pavokta-patch-3, pavokta-patch-5
- [-] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [-] The correct base branch is being used, if not `main`
- [-] I have added tests to validate that the change in functionality is working as expected

fix: updates and fixes to several pages

---

.github/dependabot.yml
docusaurus.config.js
package-lock.json
package.json
src/pages/api/service.tsx
src/theme/NavbarItem/NavbarNavLink.tsx
src/theme/prism-include-languages.ts

Show all posts under blog and update dependencies
The previous iteration only showed the most recent ones

chore: show all posts in blog (vs only recent)

---

docs/content/getting-started/perform-list-users.mdx

- Adjusted the introduction copy to provide additional detail on the utility of listUsers
- Added a model example prior to the API call examples aligned with those examples
- Adjusted the section header capitalization in line with other recent page updates
- [ X] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ -] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [- ] The correct base branch is being used, if not `main`
- [ X] I have added tests to validate that the change in …

fix(docs): update listUsers documentation

---

docs/content/modeling/conditions.mdx

Removed outdated limitation notation per @rhamzeh 
Also updated section cases in line with current style 
Closes #836

Remove outdated conditions limitation note / fix section header cases

---

docs/content/getting-started/setup-openfga/configure-openfga.mdx
docs/content/getting-started/setup-openfga/docker-setup.mdx
docs/content/intro.mdx

Adding documentation to support openfga/openfga#1615

feat: add documentation for running with SQLite database

---

docs/content/getting-started/configure-telemetry.mdx
docs/sidebars.js

This pull request adds documentation for the recent introductions of OpenTelemetry support in our SDKs.

docs: add OpenTelemetry documentation

---

docs/content/getting-started/setup-openfga/access-control.mdx

Update access control environment variable

---

blog/authors.yml
blog/fine-grained-news-2024-10.md
static/img/blog/fgn-2024-10-andrea-chiarelli.jpeg
static/img/blog/fgn-2024-10-andres-aguiar.jpg
static/img/blog/fgn-2024-10-kiah-imani.jpeg
static/img/blog/fgn-2024-10-ryanpq.jpg

Added October 20204 Fine Grained News content, as well as updated the authors.yml file to add author's image link
PR introduces the draft for the October 2024 edition of Fine Grained News, the OpenFGA newsletter.
This is a draft PR, and additional content or revisions will be needed before being marked ready for review. Feedback is welcome, especially:
- Clarity and tone of the newsletter content.
- Any missing information or corrections.

feat(blog): Added Fine Grained News October 2024 Community Edition and related files

---

docs/content/modeling/testing-models.mdx

chore: fixed list_users tests

---

docs/content/modeling/migrating/overview.mdx

chore: added more content to the migration section

---

src/components/Docs/SnippetViewer/ReadChangesRequestViewer.tsx

Read changes API uses GET instead of POST.
Close https://github.com/openfga/openfga.dev/issues/903

fix: correct read changes curl snippet

---

docs/content/getting-started/perform-check.mdx
docs/content/getting-started/production-best-practices.mdx

In #878 we forgot to add documentation around these two batch-check-related configuration variables.

feat: add batch check configuration vars

---

docs/content/community.mdx

Updated Community page to add LinkedIn page

fix (add social account): Update community.mdx

---

src/components/Docs/SnippetViewer/CheckRequestViewer.tsx

Fixed documentation template `CheckRequestViewer.tsx` for java

fix: fixed CheckRequestViewer for java

---

docs/content/getting-started/perform-check.mdx
docs/content/interacting/relationship-queries.mdx
src/components/Docs/SnippetViewer/BatchCheckRequestViewer.tsx
src/components/Docs/SnippetViewer/CheckRequestViewer.tsx

Adds the SDKs to the BatchCheckViewer
Bulk of the changes are here: https://openfga.dev/pr-preview/pr-950/docs/getting-started/perform-check#03-calling-batch-check-api

feat(docs): add SDKs to BatchCheckViewer

---

src/components/Docs/SnippetViewer/BatchCheckRequestViewer.tsx

Adds example code for calling the updated `batchCheck` method in Java.

feat: add docs for java batch check

---

docs/content/modeling/getting-started.mdx

This PR Fixes an editorial errata in the modeling/getting-started document

docs: correct and editorial errata in the modeling/getting-started doc

---

src/components/Docs/SnippetViewer/BatchCheckRequestViewer.tsx

Update `correlation_id` to `correlationId` in node.js batch check sample code.

Update correlation_id to correlationId in batch check Node.js sample code

---

blog/fine-grained-news-2025-02.md
docs/content/getting-started/setup-openfga/access-control.mdx

https://openfga.dev/pr-preview/pr-970/blog/fine-grained-news-2025-02

feat: add February FGN

---

src/components/Docs/SnippetViewer/CheckRequestViewer.tsx
src/components/Docs/SnippetViewer/ExpandRequestViewer.tsx
src/components/Docs/SnippetViewer/ListObjectsRequestViewer.tsx
src/components/Docs/SnippetViewer/ListUsersRequestViewer.tsx
src/components/Docs/SnippetViewer/WriteAuthzModelViewer.tsx
src/components/Docs/SnippetViewer/WriteRequestViewer.tsx

fix: JS examples to use authorizationModelId

---

docs/content/best-practices/adoption-patterns.mdx

chore: fix typos and formatting

---

.github/workflows/deploy.yml
docs/content/getting-started/setup-openfga/configuration.mdx
package.json

Update the config page on every build for now and to redeploy main nightly

chore: update config page on every build

---

docs/content/best-practices/modeling.mdx

chore: add relations

---

docusaurus.config.js

add `worker-src` directive to allow for same-domain service worker script execution

fix: update csp directive to restore search service worker

---

docs/content/configuration-language.mdx
docs/content/modeling/getting-started.mdx
src/components/Docs/AuthorizationModel/AuthzModelCodeBlock.tsx
src/components/Docs/AuthorizationModel/AuthzModelSnippetViewer.tsx
src/components/Docs/AuthorizationModel/SyntaxTransformer.ts

Remove superfluous JSON model examples from docs

feat(openfga): remove almost all DSL/JSON tabs with 1 exception

---

docs/content/getting-started/setup-openfga/configure-openfga.mdx

It was introduced in https://github.com/open-telemetry/opentelemetry.io/pull/2761, https://github.com/open-telemetry/opentelemetry.io/pull/2848
fixes lint errors https://github.com/openfga/openfga.dev/actions/runs/15674645618/job/44152083967?pr=1055#step:4:116

fix: update docs url for OpenTelemetry collector
